version: '3'
services: 
    minio-rest-api:
        build: .
        container_name: "mrapi-container"
        ports: 
            - "8000:15400"
        environment: 
            TZ: "Europe/Sarajevo"
        volumes: 
            - ./minio_rest_api/:/minio_rest_api
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            
        